version: '3.8'

services:
  mariadb:
    image: mariadb:11.8
    container_name: meu_mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: blogappdb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-alunos:
    image: loesterbotelho/blog-api:1.0.0
    container_name: blog-api-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/blogappdb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=America/Sao_Paulo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mariadb_data: