module(load="imtcp")
input(type="imtcp" port="514")

module(load="imudp")
input(type="imudp" port="514")

$DirCreateMode 0755
$FileCreateMode 0644

template(
    name="RemoteLogs"
    type="string"
    string="/logs/%$YEAR%-%$MONTH%-%$DAY%/%hostname%.txt"
)

*.* ?RemoteLogs

& stop